vector_store:
  type: "faiss"  # was "astra_db"

faiss:
  index_path: "faiss_index"  # where your FAISS index is saved locally

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "models/gemini-1.5-flash-8b"  
